[
    {
        "cam_no": "1",
        "camera_name": "Test1",
        "Latitude": "12.908753",
        "Longitude": "100.855225",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-001",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test1",
        "Offline_duration": "0"
    },
    {
        "cam_no": "2",
        "camera_name": "Test2",
        "Latitude": "12.946922",
        "Longitude": "100.942448",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-002",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test2",
        "Offline_duration": "0"
    },
    {
        "cam_no": "3",
        "camera_name": "Test3",
        "Latitude": "12.961625",
        "Longitude": "100.947069",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-003",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test3",
        "Offline_duration": "0"
    },
    {
        "cam_no": "4",
        "camera_name": "Test4",
        "Latitude": "12.952635",
        "Longitude": "100.944514",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-004",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test4",
        "Offline_duration": "0"
    },
    {
        "cam_no": "5",
        "camera_name": "Test5",
        "Latitude": "12.954626",
        "Longitude": "100.926990",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-005",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test5",
        "Offline_duration": "0"
    },
    {
        "cam_no": "6",
        "camera_name": "Test6",
        "Latitude": "12.945969",
        "Longitude": "100.857953",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-006",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test6",
        "Offline_duration": "0"
    },
    {
        "cam_no": "7",
        "camera_name": "Test7",
        "Latitude": "12.963328",
        "Longitude": "100.858923",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-007",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test7",
        "Offline_duration": "0"
    },
    {
        "cam_no": "8",
        "camera_name": "Test8",
        "Latitude": "12.913986",
        "Longitude": "100.850802",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-008",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test8",
        "Offline_duration": "0"
    },
    {
        "cam_no": "9",
        "camera_name": "Test9",
        "Latitude": "12.989511",
        "Longitude": "100.890669",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-009",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test9",
        "Offline_duration": "0"
    },
    {
        "cam_no": "10",
        "camera_name": "Test10",
        "Latitude": "12.995228",
        "Longitude": "100.853177",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-010",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test10",
        "Offline_duration": "0"
    },
    {
        "cam_no": "11",
        "camera_name": "Test11",
        "Latitude": "12.907385",
        "Longitude": "100.851968",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-011",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test11",
        "Offline_duration": "0"
    },
    {
        "cam_no": "12",
        "camera_name": "Test12",
        "Latitude": "12.917036",
        "Longitude": "100.929044",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-012",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test12",
        "Offline_duration": "0"
    },
    {
        "cam_no": "13",
        "camera_name": "Test13",
        "Latitude": "12.939794",
        "Longitude": "100.925179",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-013",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test13",
        "Offline_duration": "0"
    },
    {
        "cam_no": "14",
        "camera_name": "Test14",
        "Latitude": "12.970771",
        "Longitude": "100.906418",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-014",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test14",
        "Offline_duration": "0"
    },
    {
        "cam_no": "15",
        "camera_name": "Test15",
        "Latitude": "12.947146",
        "Longitude": "100.903616",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-015",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test15",
        "Offline_duration": "0"
    },
    {
        "cam_no": "16",
        "camera_name": "Test16",
        "Latitude": "12.937635",
        "Longitude": "100.932894",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-016",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test16",
        "Offline_duration": "0"
    },
    {
        "cam_no": "17",
        "camera_name": "Test17",
        "Latitude": "12.977034",
        "Longitude": "100.902379",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-017",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test17",
        "Offline_duration": "0"
    },
    {
        "cam_no": "18",
        "camera_name": "Test18",
        "Latitude": "12.977330",
        "Longitude": "100.865102",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-018",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test18",
        "Offline_duration": "0"
    },
    {
        "cam_no": "19",
        "camera_name": "Test19",
        "Latitude": "12.991835",
        "Longitude": "100.920785",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-019",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test19",
        "Offline_duration": "0"
    },
    {
        "cam_no": "20",
        "camera_name": "Test20",
        "Latitude": "12.971931",
        "Longitude": "100.857179",
        "Location": null,
        "Project": "RCS",
        "SubPro": "RCS",
        "NewCode": "RC-020",
        "NVR": null,
        "Contract": "-",
        "cctv_Online_status": "Online",
        "online_cause": "",
        "online_other_cause": null,
        "cctv_position": "ปกติ",
        "position_symptom": "",
        "position_other_symptom": null,
        "cctv_clear": "ปกติ",
        "clear_symptom": "",
        "clear_other_symptom": null,
        "cctv_record": "ปกติ",
        "record_symptom": "",
        "record_other_symptom": null,
        "cctv_Overall_status": "ปกติ",
        "Last Update": "2025-04-20 20:00:00",
        "Use Status": "ใช้งาน",
        "Use_Status_Date": "2025-04-20",
        "Not_Use_date": "0000-00-00",
        "Label": "Test20",
        "Offline_duration": "0"
    }
]